server:
  port: 8082

spring:
  application:
    name: worker-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chronogrid

worker:
  max-concurrent-jobs: 5
  instance-id: worker-1

# Ye wali line missing thi! 👇
coordinator:
  url: http://localhost:8086

logging:
  level:
    com.agrim.worker: INFO